import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';

import { Button, Toaster, Typography } from '@/src/components/ui';
import { ROUTES } from '@/src/utils/constants';

import { Providers } from './providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = async ({ children }: RootLayoutProps) => (
  <html lang='en'>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Providers
        theme={{
          enableSystem: true,
          attribute: 'class',
          defaultTheme: 'system',
          disableTransitionOnChange: true
        }}
      >
        <Toaster duration={3000} />
        <div className='relative min-h-screen overflow-hidden'>
          <header className='border-muted-foreground border-b'>
            <div className='px-6 py-4'>
              <nav className='flex items-center gap-6'>
                <Typography className='font-bold'>BUG-DRIVEN UI</Typography>
                <Button className='cursor-pointer' variant='ghost'>
                  <Link href={ROUTES.MAIN}>Главная</Link>
                </Button>
              </nav>
            </div>
          </header>
          <div className='h-[calc(100vh-72px)] overflow-auto'>{children}</div>
        </div>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
