import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { Providers } from './providers';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers
          theme={{
            enableSystem: true,
            attribute: 'class',
            defaultTheme: 'system',
            disableTransitionOnChange: true
          }}
        >
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
