name: deploy-frontend.yml

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build (SSR)
        run: yarn build

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare tags
        id: meta
        run: |
          SHA_TAG=frontend-ssr-${GITHUB_SHA::12}
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "latest_tag=frontend-ssr-latest" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -f Dockerfile \
            -t darktype/bdui-x:${{ steps.meta.outputs.latest_tag }} \
            -t darktype/bdui-x:${{ steps.meta.outputs.sha_tag }} .

      - name: Push image
        run: |
          docker push darktype/bdui-x:${{ steps.meta.outputs.latest_tag }}
          docker push darktype/bdui-x:${{ steps.meta.outputs.sha_tag }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/deploy/app
            docker pull darktype/bdui-x:frontend-ssr-latest
            docker compose up -d --no-deps frontend
            docker compose exec nginx nginx -s reload || true
            docker image prune -f
